### ISSUE TITLE
Set value from feeder to map

### ISSUE THREAD

**Issue by Sato-Kimura** [phiSgr/gatling-grpc#11]
I have 1 feeder
var myFeeder = new Feeder[String] {
    override def hasNext = true

    override def next: Map[String, String] = {

      var tmpRequest = requestQueue.poll()
      Map(
        "merchantTransID" -> tmpRequest.dataObj.merchantTransID,
        "initAmount" -> tmpRequest.dataObj.amount,
        "merchantID" -> tmpRequest.merchantID,
        "time" -> tmpRequest.time,
        "data" -> tmpRequest.data,
        "sig" -> tmpRequest.sig
      )
    }
  }
how to set value from feeder to map
val scn = scenario(this.getClass.getName)
    .feed(myFeeder)
    .exec(
      grpc(session => this.getClass.getName)
        .rpc(ZPBaseGrpc.METHOD_SEND_REQUEST)
        .payload(GrpcBaseRequest.newBuilder().setMethodName("core/cashin")
        .putParams("time", $("time").asInstanceOf[String])
         .build())
        .extract(_.getResponse.some)(_ saveAs "response")
    )
Please help me

**Comment by phiSgr** [comment]
As I have stated in [your previous issue](https://github.com/phiSgr/gatling-grpc/issues/10#issuecomment-497205741), my code is not supposed to be used with generated Java protobuf classes.

> You lose the extraction and modification capability powered by the ScalaPB lenses.

Due to the "wrapped" nature of expressions, combining the session attributes into protobuf messages will normally take some boilerplate code.
With the `:~` operator it can be written cleanly. But they only work with ScalaPB generated classes.

It is possible to force things to work by writing some more code in an [`exec` block](https://gatling.io/docs/3.1/general/scenario/#exec). However I am not going to encourage an unsupported usage with an example.

For more information on using ScalaPB with Maven, please see the following link.
https://scalapb.github.io/faq.html#how-do-i-use-scalapb-with-maven
