### ISSUE TITLE
How to use connect ssl to server by grpc + gatling?

### ISSUE THREAD

**Issue by ducquyen2509** [phiSgr/gatling-grpc#12]
I have a problem connecting to the required server with ssl. Please help me this problem.

**Comment by phiSgr** [comment]
I don't want to sound hostile, but I do feel the need to quote [How To Ask Questions The Smart Way](http://www.catb.org/~esr/faqs/smart-questions.html).

> Describe the symptoms of your problem or bug carefully and clearly.

Yes I know you have a problem. What I DON'T know, is what your problem is.

**Comment by ducquyen2509** [comment]
[ERROR]: preparation crashed: INTERNAL: http2  exception
because my server requires ssl to be requested when I request but I don't know what to do

**Comment by phiSgr** [comment]
Without even the testing code, I can only give general statements.

Gatling-gRPC does not control the connections itself. It only takes a `ManagedChannelBuilder` and uses that to create `ManagedChannel`s for the virtual users.

To know if you correctly configured the `ManagedChannelBuilder`, you can write another client in Java (or Kotlin, or Scala...) and see if you can connect to the server. If that fails, you should consult the gRPC documentation.

If you can connect to the server otherwise, but not when you uses Gatling-gRPC, I will be very happy to look into the details.

**Comment by phiSgr** [comment]
I have a hunch that you kept the `.usePlaintext()` from the examples.

**Comment by ducquyen2509** [comment]
It work. thanks you

**Comment by phiSgr** [comment]
I am curious. Before you ask this question, where did you look for information?
In which language is your gRPC client written? I assume it is not Java because otherwise you would be using the same API in the application code and not miss that method. Does the gRPC API in that language provide a similar toggle?
