### ISSUE TITLE
Example project for usage with the Maven Gatling plugin

### ISSUE THREAD

**Issue by alphaville76** [phiSgr/gatling-grpc#56]
At the moment there is an example project based on gradle.
It would be great to link to an example project based on maven.

**Comment by alphaville76** [comment]
Just done! :-) look at https://github.com/alphaville76/gatling-grpc-maven-demo

I'm very glad to receive your feedback!

**Comment by phiSgr** [comment]
Would be great if that project is forked from the gradle demo.

**Comment by phiSgr** [comment]
The benefit of having the project being forked, instead of copying the code to a new project is that:
Upstream changes are noticeable by reader of the Maven project, even if the Maven project itself is not updated.

The recent changes in the Gradle project are [this commit](https://github.com/phiSgr/gatling-grpc-gradle-demo/commit/66bdd82e631b3b41216f8641280ee04ffa7f209f) that bumps the versions,
and the [demo for Kotlin POC](https://github.com/phiSgr/gatling-grpc-gradle-demo/tree/kotlin#kotlin).

**Comment by phiSgr** [comment]
Feel free to reopen.
